version: '3.8'
services:
  web:
    image: emiliowilcar/desktop-deployweb
    container_name: desk-deploy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       ports:
        - "80:80"
        - "443:443"   
